version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  master:
    build: ./project_2_rumah123/cluster
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./project_2_rumah123/brankas_data:/app/brankas_data
    command: /app/wait-for-it.sh redis python /app/core/master_orchestrator.py


  worker:
    build: ./project_2_rumah123/cluster
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./project_2_rumah123/brankas_data:/app/brankas_data
    command: /app/wait-for-it.sh redis scrapy crawl rumah123_spider
